---
# config.yaml
# This file contains the configuration for the multipass instances
git_host: github.com # gitlab.com or github.com
git_username: langburd # Use your git* username
git_repository: ansible-pihole-cluster # Use the name of the repository
windows_switch_name: MultipassExternalSwitch # Name of the switch to use for the Windows VM
ssh_key: /Users/avi.langburd/.ssh/ubuntu
ssh_key_pub: /Users/avi.langburd/.ssh/ubuntu.pub
instances:
  # - name: pihole1
  #   ip: 192.168.8.53/23
  #   gateway: 192.168.8.1
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  # - name: pihole2
  #   ip: 192.168.8.153/23
  #   gateway: 192.168.8.1
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  - name: pihole3
    ip: 192.168.9.153/23
    gateway: 192.168.8.1
    dns:
      - 1.1.1.1
      - 1.0.0.1
